// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 Rindogatan LLC

/**
 * The words of the four register PDFs (AI system register, assessment
 * portfolio, model inventory, compliance summary) and of the audit-trail CSV,
 * in English and Spanish.
 *
 * English is exactly what those files printed before they had a language; a
 * test holds it there. Spanish uses the terms of the screens (the `common`
 * namespace of src/i18n/messages/es.json) and of the Spanish text of
 * Regulation (EU) 2024/1689 (proveedor, responsable del despliegue).
 *
 * Enum values print as stored, de-snaked, in English; in Spanish they print
 * as the screens name them, and an unknown value falls back to the English
 * form rather than disappearing.
 *
 * Pure module: no Prisma, no React, no Next.
 */

import { readLocale } from "@/lib/locale-cookie";

export type PdfLocale = "en" | "es";

/**
 * ?locale= wins; otherwise the `locale` cookie the screens use (read from the
 * Cookie header the way next-intl reads it); otherwise English.
 */
export function exportLocale(param: string | null | undefined, cookieHeader: string | null | undefined): PdfLocale {
  if (param === "es" || param === "en") return param;
  return readLocale(cookieHeader);
}

const deSnake = (key: string) => key.replace(/_/g, " ");

const STATUS_ES: Record<string, string> = {
  DRAFT: "Borrador",
  DEVELOPMENT: "En desarrollo",
  TESTING: "En pruebas",
  DEPLOYED: "Desplegado",
  RETIRED: "Retirado",
  IN_PROGRESS: "En curso",
  UNDER_REVIEW: "En revisión",
  APPROVED: "Aprobado",
  REJECTED: "Rechazado",
  PENDING: "Pendiente",
  COMPLIANT: "Conforme",
  PARTIALLY_COMPLIANT: "Parcialmente conforme",
  NON_COMPLIANT: "No conforme",
  NOT_APPLICABLE: "No aplicable",
  NOT_ASSESSED: "Sin evaluar",
};

const RISK_ES: Record<string, string> = {
  UNACCEPTABLE: "Inaceptable",
  HIGH: "Alto",
  LIMITED: "Limitado",
  MINIMAL: "Mínimo",
  UNCLASSIFIED: "Sin clasificar",
};

const TECHNIQUE_ES: Record<string, string> = {
  MACHINE_LEARNING: "Aprendizaje automático",
  DEEP_LEARNING: "Aprendizaje profundo",
  GENERATIVE_AI: "IA generativa",
  AGENTIC_AI: "IA agéntica",
  NLP: "Procesamiento del lenguaje natural",
  COMPUTER_VISION: "Visión por ordenador",
  SPEECH_RECOGNITION: "Reconocimiento de voz",
  ROBOTICS: "Robótica",
  RULE_BASED: "Basado en reglas",
  EXPERT_SYSTEM: "Sistema experto",
  STATISTICAL: "Estadístico",
  OTHER: "Otro",
};

const ROLE_ES: Record<string, string> = {
  PROVIDER: "Proveedor",
  DEPLOYER: "Responsable del despliegue",
  IMPORTER: "Importador",
  DISTRIBUTOR: "Distribuidor",
  USER: "Usuario",
};

const ASSESSMENT_TYPE_ES: Record<string, string> = {
  FRIA: "Evaluación de impacto relativa a los derechos fundamentales",
  CONFORMITY: "Conformidad",
  AI_RISK: "Riesgo de IA",
  BIAS_FAIRNESS: "Sesgo y equidad",
  CUSTOM: "Personalizada",
};

function label(map: Record<string, string>, key: string, locale: PdfLocale): string {
  return locale === "es" ? (map[key] ?? deSnake(key)) : deSnake(key);
}

/** Lifecycle, assessment and compliance statuses. */
export const statusLabel = (key: string, locale: PdfLocale) => label(STATUS_ES, key, locale);
/** EU AI Act risk tiers; English prints the stored value unchanged. */
export const riskLabel = (key: string, locale: PdfLocale) => (locale === "es" ? (RISK_ES[key] ?? deSnake(key)) : key);
export const techniqueLabel = (key: string, locale: PdfLocale) => label(TECHNIQUE_ES, key, locale);
/** The organisation's role; English prints the stored value unchanged. */
export const roleLabel = (key: string, locale: PdfLocale) => (locale === "es" ? (ROLE_ES[key] ?? deSnake(key)) : key);
export const assessmentTypeLabel = (key: string, locale: PdfLocale) => label(ASSESSMENT_TYPE_ES, key, locale);

const SHARED = {
  en: {
    generated: "Generated",
    confidential:
      "CONFIDENTIAL — This document contains sensitive information about AI governance and compliance. Distribution should be limited to authorized personnel.",
    generatedBy: "Generated by AI Sentinel",
    noRecords: "No records",
    executiveSummary: "Executive Summary",
    count: "Count",
    percentage: "Percentage",
    status: "Status",
    type: "Type",
    riskLevel: "Risk Level",
    riskDistribution: "Risk Distribution",
    statusDistribution: "Status Distribution",
    aiSystem: "AI System",
    aiSystems: "AI Systems",
    provider: "Provider",
    providers: "Providers",
    version: "Version",
    yes: "Yes",
    no: "No",
  },
  es: {
    generated: "Generado",
    confidential:
      "CONFIDENCIAL. Este documento contiene información sensible sobre la gobernanza de la IA y el cumplimiento normativo. Su difusión debe limitarse al personal autorizado.",
    generatedBy: "Generado con AI Sentinel",
    noRecords: "Sin registros",
    executiveSummary: "Resumen ejecutivo",
    count: "Número",
    percentage: "Porcentaje",
    status: "Estado",
    type: "Tipo",
    riskLevel: "Nivel de riesgo",
    riskDistribution: "Distribución por nivel de riesgo",
    statusDistribution: "Distribución por estado",
    aiSystem: "Sistema de IA",
    aiSystems: "Sistemas de IA",
    provider: "Proveedor",
    providers: "Proveedores",
    version: "Versión",
    yes: "Sí",
    no: "No",
  },
} as const;

const REGISTER = {
  en: {
    title: "AI System Register",
    subtitle: "Complete inventory of AI systems under governance",
    totalSystems: "Total Systems",
    deployed: "Deployed",
    highOrUnacceptable: "High / Unacceptable Risk",
    draft: "Draft",
    systemOverview: "System Overview",
    systemName: "System Name",
    technique: "Technique",
    role: "Role",
    models: "Models",
    businessOwner: "Business Owner",
    technicalOwner: "Technical Owner",
    vendor: "Vendor",
    deploymentDate: "Deployment Date",
    retirementDate: "Retirement Date",
    processesPersonalData: "Processes Personal Data",
    dataSources: "Data Sources",
    assessments: "Assessments",
    incidents: "Incidents",
    complianceMappings: "Compliance Mappings",
    description: "Description",
    rationale: "Risk Classification Rationale",
  },
  es: {
    title: "Registro de sistemas de IA",
    subtitle: "Inventario completo de los sistemas de IA sujetos a gobernanza",
    totalSystems: "Sistemas en total",
    deployed: "Desplegados",
    highOrUnacceptable: "Riesgo alto o inaceptable",
    draft: "Borrador",
    systemOverview: "Resumen de los sistemas",
    systemName: "Nombre del sistema",
    technique: "Técnica",
    role: "Rol",
    models: "Modelos",
    businessOwner: "Responsable de negocio",
    technicalOwner: "Responsable técnico",
    vendor: "Proveedor externo",
    deploymentDate: "Fecha de despliegue",
    retirementDate: "Fecha de retirada",
    processesPersonalData: "Trata datos personales",
    dataSources: "Fuentes de datos",
    assessments: "Evaluaciones",
    incidents: "Incidentes",
    complianceMappings: "Correspondencias de cumplimiento",
    description: "Descripción",
    rationale: "Justificación de la clasificación del riesgo",
  },
} as const;

const PORTFOLIO = {
  en: {
    coverTitle: "AI Risk Assessment Portfolio",
    subtitle: "Overview of all AI risk assessments and their outcomes",
    title: "Assessment Portfolio",
    totalAssessments: "Total Assessments",
    approved: "Approved",
    inProgress: "In Progress",
    avgRiskScore: "Avg Risk Score",
    byType: "By Assessment Type",
    byStatus: "By Status",
    register: "Assessment Register",
    assessmentTitle: "Title",
    riskScore: "Risk Score",
    created: "Created",
    template: "Template",
    createdBy: "Created By",
    reviewedBy: "Reviewed By",
    reviewed: "Reviewed",
    approvedBy: "Approved By",
    approvedOn: "Approved",
  },
  es: {
    coverTitle: "Cartera de evaluaciones de riesgos de la IA",
    subtitle: "Resumen de todas las evaluaciones de riesgos de la IA y de sus resultados",
    title: "Cartera de evaluaciones",
    totalAssessments: "Evaluaciones en total",
    approved: "Aprobadas",
    inProgress: "En curso",
    avgRiskScore: "Puntuación media de riesgo",
    byType: "Por tipo de evaluación",
    byStatus: "Por estado",
    register: "Registro de evaluaciones",
    assessmentTitle: "Título",
    riskScore: "Puntuación de riesgo",
    created: "Creada",
    template: "Plantilla",
    createdBy: "Creada por",
    reviewedBy: "Revisada por",
    reviewed: "Revisada",
    approvedBy: "Aprobada por",
    approvedOn: "Aprobada",
  },
} as const;

const INVENTORY = {
  en: {
    title: "AI Model Inventory",
    subtitle: "Complete catalogue of AI models across all systems",
    totalModels: "Total Models",
    highRisk: "High Risk",
    modelRegister: "Model Register",
    modelName: "Model Name",
    risk: "Risk",
    byProvider: "By Provider",
    byModelType: "By Model Type",
    unknown: "Unknown",
    unspecified: "Unspecified",
    unknownProvider: "Unknown provider",
    systemStatus: "System Status",
    trainingData: "Training Data Summary",
    limitations: "Known Limitations",
  },
  es: {
    title: "Inventario de modelos de IA",
    subtitle: "Catálogo completo de los modelos de IA de todos los sistemas",
    totalModels: "Modelos en total",
    highRisk: "Riesgo alto",
    modelRegister: "Registro de modelos",
    modelName: "Nombre del modelo",
    risk: "Riesgo",
    byProvider: "Por proveedor",
    byModelType: "Por tipo de modelo",
    unknown: "Desconocido",
    unspecified: "Sin especificar",
    unknownProvider: "Proveedor desconocido",
    systemStatus: "Estado del sistema",
    trainingData: "Resumen de los datos de entrenamiento",
    limitations: "Limitaciones conocidas",
  },
} as const;

const COMPLIANCE = {
  en: {
    coverTitle: (framework: string) => `${framework} Compliance Summary`,
    coverSubtitle: (system: string) => `Assessment for ${system}`,
    title: "Compliance Summary",
    framework: "Framework",
    requirements: "Requirements",
    compliant: "Compliant",
    partial: "Partial",
    nonCompliant: "Non-Compliant",
    progress: (pct: number) => `Compliance Progress (${pct}% of assessed)`,
    statusBreakdown: "Status Breakdown",
    compliantRow: "Compliant",
    nonCompliantRow: "Non-Compliant",
    partiallyCompliant: "Partially Compliant",
    notAssessed: "Not Assessed",
    notApplicable: "Not Applicable",
    requirementDetails: "Requirement Details",
    code: "Code",
    requirement: "Requirement",
    evidence: "Evidence",
    actionRequired: "Non-Compliant Requirements — Action Required",
  },
  es: {
    coverTitle: (framework: string) => `Resumen de cumplimiento: ${framework}`,
    coverSubtitle: (system: string) => `Evaluación de ${system}`,
    title: "Resumen de cumplimiento",
    framework: "Marco",
    requirements: "Requisitos",
    compliant: "Conformes",
    partial: "Parciales",
    nonCompliant: "No conformes",
    progress: (pct: number) => `Grado de cumplimiento (${pct} % de lo evaluado)`,
    statusBreakdown: "Desglose por estado",
    compliantRow: "Conforme",
    nonCompliantRow: "No conforme",
    partiallyCompliant: "Parcialmente conforme",
    notAssessed: "Sin evaluar",
    notApplicable: "No aplicable",
    requirementDetails: "Detalle de los requisitos",
    code: "Código",
    requirement: "Requisito",
    evidence: "Evidencias",
    actionRequired: "Requisitos no conformes: actuación necesaria",
  },
} as const;

const AUDIT = {
  en: {
    header: [
      "Timestamp (UTC)",
      "Action",
      "Entity type",
      "Entity id",
      "Actor name",
      "Actor email",
      "Actor id",
      "Changes",
      "Metadata",
    ],
    organisation: "Organisation",
    rows: "Rows",
    truncated: (max: number) => ` (truncated at the ${max} row limit; narrow the date range)`,
    filters: "Filters",
    none: "none",
    filename: "Audit-Trail",
  },
  es: {
    header: [
      "Fecha y hora (UTC)",
      "Acción",
      "Tipo de entidad",
      "Id. de la entidad",
      "Nombre de quien actúa",
      "Correo de quien actúa",
      "Id. de quien actúa",
      "Cambios",
      "Metadatos",
    ],
    organisation: "Organización",
    rows: "Filas",
    truncated: (max: number) => ` (recortado en el límite de ${max} filas; acota el intervalo de fechas)`,
    filters: "Filtros",
    none: "ninguno",
    filename: "Registro-de-auditoria",
  },
} as const;

export const pdfLabels = (locale: PdfLocale) => ({
  ...SHARED[locale],
  register: REGISTER[locale],
  portfolio: PORTFOLIO[locale],
  inventory: INVENTORY[locale],
  compliance: COMPLIANCE[locale],
  audit: AUDIT[locale],
});

export type PdfLabels = ReturnType<typeof pdfLabels>;
