// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 Rindogatan LLC

/**
 * Mock ProgramGraph used by unit tests, the dev preview route
 * (/preview/program-map), and PDF visual QA. Law-firm-shaped, with
 * deliberate gaps (one unclassified system, an overdue gate, unlinked
 * policies, missing transparency profiles) so every encoding state renders.
 */

import type { ProgramGraph } from "../types";

export const MOCK_PROGRAM_GRAPH: ProgramGraph = {
  groups: [
    { id: "GENERAL_ASSISTANT", label: "General AI Assistants", rolloutStage: "ADOPT" },
    { id: "LEGAL_RESEARCH", label: "Legal Research AI", rolloutStage: "ADOPT" },
    { id: "CONTRACT_CLM", label: "Contract Drafting & Review AI", rolloutStage: "PILOT" },
    { id: "EDISCOVERY", label: "E-Discovery & Document Review AI", rolloutStage: "PILOT" },
    { id: "TRANSCRIPTION_DICTATION", label: "Transcription & Dictation AI", rolloutStage: "RESTRICT" },
  ],
  systems: [
    {
      id: "sys-chatgpt",
      name: "ChatGPT",
      groupId: "GENERAL_ASSISTANT",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-openai",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PASSED", overdue: false }],
      policyLinkCount: 2,
      transparencyRelevant: true,
      hasTransparencyProfile: true,
      complianceAssessedPct: 62,
    },
    {
      id: "sys-claude",
      name: "Claude",
      groupId: "GENERAL_ASSISTANT",
      riskLevel: "LIMITED",
      status: "DRAFT",
      processesPersonalData: true,
      vendorId: "ven-anthropic",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PENDING", overdue: false }],
      policyLinkCount: 0,
      transparencyRelevant: true,
      hasTransparencyProfile: false,
      complianceAssessedPct: 0,
    },
    {
      id: "sys-copilot",
      name: "Microsoft 365 Copilot",
      groupId: "GENERAL_ASSISTANT",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-microsoft",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PENDING", overdue: true }],
      policyLinkCount: 1,
      transparencyRelevant: true,
      hasTransparencyProfile: false,
      complianceAssessedPct: 15,
    },
    {
      id: "sys-lexis",
      name: "Lexis+ AI",
      groupId: "LEGAL_RESEARCH",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-lexisnexis",
      gates: [],
      policyLinkCount: 1,
      transparencyRelevant: true,
      hasTransparencyProfile: true,
      complianceAssessedPct: 48,
    },
    {
      id: "sys-westlaw",
      name: "Westlaw Precision AI",
      groupId: "LEGAL_RESEARCH",
      riskLevel: null, // deliberately unclassified — the visible gap
      status: "TESTING",
      processesPersonalData: true,
      vendorId: "ven-thomson",
      gates: [],
      policyLinkCount: 0,
      transparencyRelevant: true,
      hasTransparencyProfile: false,
      complianceAssessedPct: null,
    },
    {
      id: "sys-harvey",
      name: "Harvey",
      groupId: "CONTRACT_CLM",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-harvey",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PASSED", overdue: false }],
      policyLinkCount: 3,
      transparencyRelevant: true,
      hasTransparencyProfile: true,
      complianceAssessedPct: 81,
    },
    {
      id: "sys-cocounsel",
      name: "CoCounsel",
      groupId: "CONTRACT_CLM",
      riskLevel: "LIMITED",
      status: "DEVELOPMENT",
      processesPersonalData: true,
      vendorId: "ven-thomson",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "IN_REVIEW", overdue: false }],
      policyLinkCount: 0,
      transparencyRelevant: true,
      hasTransparencyProfile: false,
      complianceAssessedPct: 5,
    },
    {
      id: "sys-luminance",
      name: "Luminance",
      groupId: "CONTRACT_CLM",
      riskLevel: "HIGH",
      status: "TESTING",
      processesPersonalData: true,
      vendorId: "ven-luminance",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PENDING", overdue: false }],
      policyLinkCount: 1,
      transparencyRelevant: true,
      hasTransparencyProfile: false,
      complianceAssessedPct: 10,
    },
    {
      id: "sys-relativity",
      name: "Relativity aiR",
      groupId: "EDISCOVERY",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-relativity",
      gates: [{ gateType: "PRE_DEPLOYMENT", status: "PASSED", overdue: false }],
      policyLinkCount: 2,
      transparencyRelevant: false,
      hasTransparencyProfile: false,
      complianceAssessedPct: 55,
    },
    {
      id: "sys-everlaw",
      name: "Everlaw",
      groupId: "EDISCOVERY",
      riskLevel: "MINIMAL",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-everlaw",
      gates: [],
      policyLinkCount: 0,
      transparencyRelevant: false,
      hasTransparencyProfile: false,
      complianceAssessedPct: 30,
    },
    {
      id: "sys-otter",
      name: "Otter AI",
      groupId: "TRANSCRIPTION_DICTATION",
      riskLevel: "LIMITED",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-otter",
      gates: [],
      policyLinkCount: 1,
      transparencyRelevant: false,
      hasTransparencyProfile: false,
      complianceAssessedPct: 40,
    },
    {
      id: "sys-dragon",
      name: "Dragon Professional",
      groupId: "TRANSCRIPTION_DICTATION",
      riskLevel: "MINIMAL",
      status: "DEPLOYED",
      processesPersonalData: true,
      vendorId: "ven-microsoft",
      gates: [],
      policyLinkCount: 0,
      transparencyRelevant: false,
      hasTransparencyProfile: false,
      complianceAssessedPct: null,
    },
    {
      id: "sys-orphan",
      name: "Bespoke Intake Classifier",
      groupId: "NONEXISTENT_GROUP", // exercises the implicit ungrouped lane
      riskLevel: "HIGH",
      status: "DRAFT",
      processesPersonalData: true,
      vendorId: null,
      gates: [],
      policyLinkCount: 0,
      transparencyRelevant: false,
      hasTransparencyProfile: false,
      complianceAssessedPct: null,
    },
  ],
  vendors: [
    { id: "ven-openai", name: "OpenAI", riskLevel: "MEDIUM", systemCount: 1 },
    { id: "ven-anthropic", name: "Anthropic", riskLevel: "MEDIUM", systemCount: 1 },
    { id: "ven-microsoft", name: "Microsoft", riskLevel: "MEDIUM", systemCount: 3 },
    { id: "ven-lexisnexis", name: "LexisNexis", riskLevel: "LOW", systemCount: 1 },
    { id: "ven-thomson", name: "Thomson Reuters", riskLevel: "MEDIUM", systemCount: 3 },
    { id: "ven-harvey", name: "Harvey", riskLevel: "MEDIUM", systemCount: 1 },
    { id: "ven-luminance", name: "Luminance", riskLevel: "HIGH", systemCount: 1 },
    { id: "ven-relativity", name: "Relativity", riskLevel: "MEDIUM", systemCount: 1 },
    { id: "ven-everlaw", name: "Everlaw", riskLevel: "LOW", systemCount: 1 },
    { id: "ven-otter", name: "Otter.ai", riskLevel: "MEDIUM", systemCount: 1 },
    { id: "ven-unused", name: "Unused Vendor", riskLevel: null, systemCount: 0 },
  ],
};
